---

name: Deploy Cards

on: 
  push: 
    branches: 
      - master
    paths:
      - 'Images-HT/starwars/**'
      - 'Images-HT/*.gif'
      - 'darkside.cdf'
      - 'lightside.cdf'

jobs:
  dewit: 
    runs-on: "ubuntu-latest"

    steps:
      ## https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          path: holotable

      - name: Checking working directory
        run: |
          echo
          echo "should be in /home/runner/work/holotable: [$(pwd)]"
          echo

      - name: Case Fixer
        run: |
          python3 case_fixer.py

      - name: Make gifs
        run: |
          python3 make_gif_from_pngs.py
          sleep 2s
          python3 make_t_gifs.py

      - name: Update listmd5 and create release zip
        run: |
          bash make_listmd5.sh
          python3 fix_bullets.py
          sleep 2s
          python3 make_version_dat.py
          sleep 2s
          bash make_release_zip.sh


      - name: sync to s3
        run: |
          echo "Cards"
          aws s3 sync ./Images-HT/starwars/ s3://res.starwarsccg.org/cards/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json
          echo "Legacy"
          aws s3 sync ./Images-HT/legacy/ s3://res.starwarsccg.org/cards/legacy/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json
          echo "Cloudfront Invalidation"
          aws cloudfront create-invalidation --distribution-id E4R02360UW5RJ --paths "/cards/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Commit files
        run: |
          git config --local user.email "devon+github-actions[bot]@hubner.org"
          git config --local user.name "github-actions[bot]"
          #echo '[url "git@github.com:"]' >> ~/.gitconfig
          #echo 'insteadOf = https://github.com/' >> ~/.gitconfig
          git add -A Images-HT/ ; true
          git commit -m "Fixing case and making gifs" -a ; true
          #git pull -q ; true


      ## https://github.com/ad-m/github-push-action
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


      - name: Commit updates to holotable_exe
        run: |
          echo
          echo
          echo "ls"
          ls -al
          echo
          echo "git....: [$(which git)]: $(git --version)"
          echo "python3: [$(which python3)]"
          echo "rsync..: [$(which rsync)]"
          echo
          echo "should be in /home/runner/work/holotable: [$(pwd)]"
          cd ..
          echo "should be in /home/runner/work/: [$(pwd)]"
          echo
          echo "${{ secrets.SWCCG_HOLOTABLE_EXE }}" > swccg-holotable-exe.pem
          chmod 0600 swccg-holotable-exe.pem
          echo "swccg-holotable-exe.pem info:"
          ls -al swccg-holotable-exe.pem
          export TIMESTAMP=$(date +'%Y%m%d-%H%M')
          echo
          echo "Setting GIT_SSH_COMMAND"
          export GIT_SSH_COMMAND="ssh -i swccg-holotable-exe.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          echo "git clone DiscordCardLinker"
          git clone git@github.com:swccgpc/holotable_exe.git holotable_exe
          echo
          echo "ls"
          ls -al
          echo
          ls holotable_exe
          echo
          echo "copy cdf and image files to holotable_exe"
          cd holotable_exe/
          chmod +x ./update_cards.py
          ./update_cards.py
          git add -a .
          git commit -m "${TIMESTAMP}"
          git tag "${TIMESTAMP}"
          git push origin "${TIMESTAMP}"
          cd ..
          rm swccg-holotable-exe.pem